site_name: 机器学习
site_author: ricolxwz
site_url: https://ml.ricolxwz.de
# repo_url: https://github.com/ricolxwz/ml
edit_uri: https://github.com/ricolxwz/ml/edit/master/docs
repo_name: ricolxwz/ml
copyright: <p xmlns:cc="http://creativecommons.org/ns#" >版权所有 &copy 2024 由 <span property="cc:attributionName">许文泽</span> 采用 <a href="https://creativecommons.org/licenses/by-nc/4.0/?ref=chooser-v1" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">CC BY-NC 4.0&nbsp</a>许可证发布</p>
site_description: 一个有待面面俱到的机器学习文档
theme:
  name: material
  logo_light_mode: https://cdn.jsdelivr.net/gh/sigmax0124/logo@master/favion-big-mc-212121-000000-1.svg 
  logo_dark_mode: https://cdn.jsdelivr.net/gh/sigmax0124/logo@master/favion-big-mc-000000-212121-1.svg
  language: zh
  custom_dir: overrides
  features:
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.footnote.tooltips
    - content.tooltips
    - content.action.edit
    - content.action.view
    # - header.autohide
    # - announce.dismiss
    # - navigation.footer
    - navigation.tabs
    - navitation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
    - search.share
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to system preference 
  font:
    text: "Roboto"
    code: "Ubuntu Mono"
  icon:
    annotation: material/star-four-points-circle
    repo: fontawesome/brands/github
    # admonition:
    #   note: octicons/tag-16
    #   abstract: octicons/checklist-16
    #   info: octicons/info-16
    #   tip: octicons/squirrel-16
    #   success: octicons/check-16
    #   question: octicons/question-16
    #   warning: octicons/alert-16
    #   failure: octicons/x-circle-16
    #   danger: octicons/zap-16
    #   bug: octicons/bug-16
    #   example: octicons/beaker-16
    #   quote: octicons/quote-16 
extra:
  social:
    - icon: fontawesome/compass-solid
      link: https://ricolxwz.de
    - icon: fontawesome/brands/github
      link: https://github.com/ricolxwz
    - icon: fontawesome/mug-hot-solid
      link: https://gitea.ricolxwz.io
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/ricolxwz
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/ricolxwz
    - icon: fontawesome/telegram-brands-solid
      link: https://t.me/ricolxwz
    - icon: fontawesome/at-solid
      link: mailto:ricol.xwz@outlook.com
  generator: false
extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css
  - stylesheets/extra.css
extra_javascript:
  - javascripts/favicon.js
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
  - javascripts/umami.js
markdown_extensions:
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.magiclink
  - admonition
  - abbr
  - attr_list
  - md_in_html
  - footnotes
  - def_list
  - tables
  - toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
          percent_encode: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
plugins:
  - i18n:
      enabled: !ENV [CI, false]
      docs_structure: suffix
      languages:
        - locale: zh
          default: true
          name: 中文
          build: true
        - locale: en
          name: English
          build: true
  - search:
      separator: '[\s\u200b\-]'
  - open-in-new-tab
  - glightbox:
      skip_classes:
        - skipbox
  - mkdocs-jupyter:
      theme: slate
      include_source: True
  - git-revision-date-localized:
      locale: zh
      enable_creation_date: true
      enabled: !ENV [CI, false]
  - git-committers:
      repository: ricolxwz/ml
      branch: master
      enabled: !ENV [CI, false]
nav:
  - 开始:
    - index.md
  - 概率:
    - 绪论: 概率/绪论.md
    - 随机事件和概率: 概率/随机事件与概率.md
    - 一维随机变量及其分布: 概率/一维随机变量及其分布.md
    - 多维随机变量及其分布: 概率/多维随机变量及其分布.md
    - 随机变量的数字特征: 概率/随机变量的数字特征.md
    - 大数定律与中心极限定理: 概率/大数定律与中心极限定理.md
    - 数理统计: 概率/数理统计.md
  - 算法:
    - 绪论: 算法/绪论.md
    - 线性回归: 算法/线性回归.md
    - 预处理: 算法/预处理.md
    - 最邻近: 算法/最邻近.md
    - 朴素贝叶斯: 算法/朴素贝叶斯.md
    - 评估: 算法/评估.md
    - 决策树: 算法/决策树.md
    - 集成学习: 算法/集成学习.md
    - 支持向量机: 算法/支持向量机.md
    - 降维: 算法/降维.md
    - 神经网络:
      - 前馈神经网络: 算法/神经网络/前馈神经网络.md
      - 卷积神经网络: 算法/神经网络/卷积神经网络.md
      - 循环神经网络: 算法/神经网络/循环神经网络