name: ci 
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    container: ricolxwz/mkdocs:latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
        with: 
          fetch-depth: 0
      - run: mkdocs gh-deploy --force
        env:
            MKDOCS_GIT_COMMITTERS_APIKEY: ${{ secrets.MKDOCS_GIT_COMMITTERS_APIKEY }}
