name: ci 
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  example-job:
    runs-on: ubuntu-latest
    container:
      image: node:14  # 主容器，所有步骤默认在此容器中运行
    steps:
      - name: Run Node.js script
        run: node -v  # 这步在 node:14 容器中运行

      - name: Run Python step in its own container
        uses: docker://python:3.8  # 这步在一个单独的 python 容器中运行
        run: python --version
