name: ci 
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  example-job:
    runs-on: self-hosted
    container:
      image: node:14  # 主容器，所有步骤默认在此容器中运行
    steps:
      - name: Run Node.js script
        run: node -v  # 这步在 node:14 容器中运行

      - name: Run Python script in container
        uses: docker://python:3.8  # 指定 Python 容器镜像
        with:
          entrypoint: "/bin/sh"  # 指定容器入口点

